services:
  api:
    container_name: api
    build:
      context: .
      target: runtime
      args:
        APP_ENV: ${APP_ENV}
    restart: always
    ports:
      - "${FORWARD_APP_PORT}:8000"
    env_file:
      - .env

  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - '${FORWARD_DB_PORT}:${DB_PORT}'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
